# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vrom_ai_pb2 as vrom__ai__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vrom_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TagProduct = channel.unary_unary(
                '/ai.AIService/TagProduct',
                request_serializer=vrom__ai__pb2.ProductRequest.SerializeToString,
                response_deserializer=vrom__ai__pb2.TagResponse.FromString,
                _registered_method=True)
        self.ModerateContent = channel.unary_unary(
                '/ai.AIService/ModerateContent',
                request_serializer=vrom__ai__pb2.ContentRequest.SerializeToString,
                response_deserializer=vrom__ai__pb2.ModerationResponse.FromString,
                _registered_method=True)
        self.SupportChat = channel.unary_unary(
                '/ai.AIService/SupportChat',
                request_serializer=vrom__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=vrom__ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.PredictETA = channel.unary_unary(
                '/ai.AIService/PredictETA',
                request_serializer=vrom__ai__pb2.ETARequest.SerializeToString,
                response_deserializer=vrom__ai__pb2.ETAResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TagProduct(self, request, context):
        """1. Tagging (Visual Merchandising)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModerateContent(self, request, context):
        """2. Content Moderation (Guardian)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SupportChat(self, request, context):
        """3. Customer Support (RAG)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictETA(self, request, context):
        """4. Logistics (ETA Predictor)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TagProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.TagProduct,
                    request_deserializer=vrom__ai__pb2.ProductRequest.FromString,
                    response_serializer=vrom__ai__pb2.TagResponse.SerializeToString,
            ),
            'ModerateContent': grpc.unary_unary_rpc_method_handler(
                    servicer.ModerateContent,
                    request_deserializer=vrom__ai__pb2.ContentRequest.FromString,
                    response_serializer=vrom__ai__pb2.ModerationResponse.SerializeToString,
            ),
            'SupportChat': grpc.unary_unary_rpc_method_handler(
                    servicer.SupportChat,
                    request_deserializer=vrom__ai__pb2.ChatRequest.FromString,
                    response_serializer=vrom__ai__pb2.ChatResponse.SerializeToString,
            ),
            'PredictETA': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictETA,
                    request_deserializer=vrom__ai__pb2.ETARequest.FromString,
                    response_serializer=vrom__ai__pb2.ETAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TagProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/TagProduct',
            vrom__ai__pb2.ProductRequest.SerializeToString,
            vrom__ai__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModerateContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ModerateContent',
            vrom__ai__pb2.ContentRequest.SerializeToString,
            vrom__ai__pb2.ModerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SupportChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/SupportChat',
            vrom__ai__pb2.ChatRequest.SerializeToString,
            vrom__ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictETA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/PredictETA',
            vrom__ai__pb2.ETARequest.SerializeToString,
            vrom__ai__pb2.ETAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
