# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vrom_ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vrom_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvrom_ai.proto\x12\x02\x61i\"-\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"1\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t\"j\n\nETARequest\x12\x11\n\tstart_lat\x18\x01 \x01(\x01\x12\x11\n\tstart_lng\x18\x02 \x01(\x01\x12\x0f\n\x07\x65nd_lat\x18\x03 \x01(\x01\x12\x0f\n\x07\x65nd_lng\x18\x04 \x01(\x01\x12\x14\n\x0cvehicle_type\x18\x05 \x01(\t\"@\n\x0b\x45TAResponse\x12\x19\n\x11\x65stimated_minutes\x18\x01 \x01(\x01\x12\x16\n\x0etraffic_status\x18\x02 \x01(\t\"@\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x1b\n\x0bTagResponse\x12\x0c\n\x04tags\x18\x01 \x03(\t\"*\n\x0e\x43ontentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"9\n\x12ModerationResponse\x12\x13\n\x0bis_approved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\xe6\x01\n\tAIService\x12\x33\n\nTagProduct\x12\x12.ai.ProductRequest\x1a\x0f.ai.TagResponse\"\x00\x12?\n\x0fModerateContent\x12\x12.ai.ContentRequest\x1a\x16.ai.ModerationResponse\"\x00\x12\x32\n\x0bSupportChat\x12\x0f.ai.ChatRequest\x1a\x10.ai.ChatResponse\"\x00\x12/\n\nPredictETA\x12\x0e.ai.ETARequest\x1a\x0f.ai.ETAResponse\"\x00\x42\x13P\x01Z\x0fvrom-backend/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vrom_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z\017vrom-backend/pb'
  _globals['_CHATREQUEST']._serialized_start=21
  _globals['_CHATREQUEST']._serialized_end=66
  _globals['_CHATRESPONSE']._serialized_start=68
  _globals['_CHATRESPONSE']._serialized_end=117
  _globals['_ETAREQUEST']._serialized_start=119
  _globals['_ETAREQUEST']._serialized_end=225
  _globals['_ETARESPONSE']._serialized_start=227
  _globals['_ETARESPONSE']._serialized_end=291
  _globals['_PRODUCTREQUEST']._serialized_start=293
  _globals['_PRODUCTREQUEST']._serialized_end=357
  _globals['_TAGRESPONSE']._serialized_start=359
  _globals['_TAGRESPONSE']._serialized_end=386
  _globals['_CONTENTREQUEST']._serialized_start=388
  _globals['_CONTENTREQUEST']._serialized_end=430
  _globals['_MODERATIONRESPONSE']._serialized_start=432
  _globals['_MODERATIONRESPONSE']._serialized_end=489
  _globals['_AISERVICE']._serialized_start=492
  _globals['_AISERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
