// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pb/vrom_ai.proto

// Defines the AI Service payload structure

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Support RAG Models
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_pb_vrom_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_pb_vrom_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

// ETA Predictor Models
type ETARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLat      float64                `protobuf:"fixed64,1,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLng      float64                `protobuf:"fixed64,2,opt,name=start_lng,json=startLng,proto3" json:"start_lng,omitempty"`
	EndLat        float64                `protobuf:"fixed64,3,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLng        float64                `protobuf:"fixed64,4,opt,name=end_lng,json=endLng,proto3" json:"end_lng,omitempty"`
	VehicleType   string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ETARequest) Reset() {
	*x = ETARequest{}
	mi := &file_pb_vrom_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETARequest) ProtoMessage() {}

func (x *ETARequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETARequest.ProtoReflect.Descriptor instead.
func (*ETARequest) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ETARequest) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *ETARequest) GetStartLng() float64 {
	if x != nil {
		return x.StartLng
	}
	return 0
}

func (x *ETARequest) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *ETARequest) GetEndLng() float64 {
	if x != nil {
		return x.EndLng
	}
	return 0
}

func (x *ETARequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type ETAResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EstimatedMinutes float64                `protobuf:"fixed64,1,opt,name=estimated_minutes,json=estimatedMinutes,proto3" json:"estimated_minutes,omitempty"`
	TrafficStatus    string                 `protobuf:"bytes,2,opt,name=traffic_status,json=trafficStatus,proto3" json:"traffic_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ETAResponse) Reset() {
	*x = ETAResponse{}
	mi := &file_pb_vrom_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETAResponse) ProtoMessage() {}

func (x *ETAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETAResponse.ProtoReflect.Descriptor instead.
func (*ETAResponse) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ETAResponse) GetEstimatedMinutes() float64 {
	if x != nil {
		return x.EstimatedMinutes
	}
	return 0
}

func (x *ETAResponse) GetTrafficStatus() string {
	if x != nil {
		return x.TrafficStatus
	}
	return ""
}

// Visual Merchandiser Models
type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_pb_vrom_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_pb_vrom_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{5}
}

func (x *TagResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Guardian Models
type ContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRequest) Reset() {
	*x = ContentRequest{}
	mi := &file_pb_vrom_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRequest) ProtoMessage() {}

func (x *ContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRequest.ProtoReflect.Descriptor instead.
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ContentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsApproved    bool                   `protobuf:"varint,1,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerationResponse) Reset() {
	*x = ModerationResponse{}
	mi := &file_pb_vrom_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationResponse) ProtoMessage() {}

func (x *ModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vrom_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationResponse.ProtoReflect.Descriptor instead.
func (*ModerationResponse) Descriptor() ([]byte, []int) {
	return file_pb_vrom_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ModerationResponse) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *ModerationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pb_vrom_ai_proto protoreflect.FileDescriptor

const file_pb_vrom_ai_proto_rawDesc = "" +
	"\n" +
	"\x10pb/vrom_ai.proto\x12\x02ai\"<\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"D\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\"\x9b\x01\n" +
	"\n" +
	"ETARequest\x12\x1b\n" +
	"\tstart_lat\x18\x01 \x01(\x01R\bstartLat\x12\x1b\n" +
	"\tstart_lng\x18\x02 \x01(\x01R\bstartLng\x12\x17\n" +
	"\aend_lat\x18\x03 \x01(\x01R\x06endLat\x12\x17\n" +
	"\aend_lng\x18\x04 \x01(\x01R\x06endLng\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\"a\n" +
	"\vETAResponse\x12+\n" +
	"\x11estimated_minutes\x18\x01 \x01(\x01R\x10estimatedMinutes\x12%\n" +
	"\x0etraffic_status\x18\x02 \x01(\tR\rtrafficStatus\"X\n" +
	"\x0eProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"!\n" +
	"\vTagResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"4\n" +
	"\x0eContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"M\n" +
	"\x12ModerationResponse\x12\x1f\n" +
	"\vis_approved\x18\x01 \x01(\bR\n" +
	"isApproved\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xe6\x01\n" +
	"\tAIService\x123\n" +
	"\n" +
	"TagProduct\x12\x12.ai.ProductRequest\x1a\x0f.ai.TagResponse\"\x00\x12?\n" +
	"\x0fModerateContent\x12\x12.ai.ContentRequest\x1a\x16.ai.ModerationResponse\"\x00\x122\n" +
	"\vSupportChat\x12\x0f.ai.ChatRequest\x1a\x10.ai.ChatResponse\"\x00\x12/\n" +
	"\n" +
	"PredictETA\x12\x0e.ai.ETARequest\x1a\x0f.ai.ETAResponse\"\x00B\x13P\x01Z\x0fvrom-backend/pbb\x06proto3"

var (
	file_pb_vrom_ai_proto_rawDescOnce sync.Once
	file_pb_vrom_ai_proto_rawDescData []byte
)

func file_pb_vrom_ai_proto_rawDescGZIP() []byte {
	file_pb_vrom_ai_proto_rawDescOnce.Do(func() {
		file_pb_vrom_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_vrom_ai_proto_rawDesc), len(file_pb_vrom_ai_proto_rawDesc)))
	})
	return file_pb_vrom_ai_proto_rawDescData
}

var file_pb_vrom_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_vrom_ai_proto_goTypes = []any{
	(*ChatRequest)(nil),        // 0: ai.ChatRequest
	(*ChatResponse)(nil),       // 1: ai.ChatResponse
	(*ETARequest)(nil),         // 2: ai.ETARequest
	(*ETAResponse)(nil),        // 3: ai.ETAResponse
	(*ProductRequest)(nil),     // 4: ai.ProductRequest
	(*TagResponse)(nil),        // 5: ai.TagResponse
	(*ContentRequest)(nil),     // 6: ai.ContentRequest
	(*ModerationResponse)(nil), // 7: ai.ModerationResponse
}
var file_pb_vrom_ai_proto_depIdxs = []int32{
	4, // 0: ai.AIService.TagProduct:input_type -> ai.ProductRequest
	6, // 1: ai.AIService.ModerateContent:input_type -> ai.ContentRequest
	0, // 2: ai.AIService.SupportChat:input_type -> ai.ChatRequest
	2, // 3: ai.AIService.PredictETA:input_type -> ai.ETARequest
	5, // 4: ai.AIService.TagProduct:output_type -> ai.TagResponse
	7, // 5: ai.AIService.ModerateContent:output_type -> ai.ModerationResponse
	1, // 6: ai.AIService.SupportChat:output_type -> ai.ChatResponse
	3, // 7: ai.AIService.PredictETA:output_type -> ai.ETAResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_vrom_ai_proto_init() }
func file_pb_vrom_ai_proto_init() {
	if File_pb_vrom_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_vrom_ai_proto_rawDesc), len(file_pb_vrom_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_vrom_ai_proto_goTypes,
		DependencyIndexes: file_pb_vrom_ai_proto_depIdxs,
		MessageInfos:      file_pb_vrom_ai_proto_msgTypes,
	}.Build()
	File_pb_vrom_ai_proto = out.File
	file_pb_vrom_ai_proto_goTypes = nil
	file_pb_vrom_ai_proto_depIdxs = nil
}
