// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/vrom_engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	RadiusKm      uint32                 `protobuf:"varint,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyRequest) Reset() {
	*x = NearbyRequest{}
	mi := &file_proto_vrom_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyRequest) ProtoMessage() {}

func (x *NearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vrom_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyRequest.ProtoReflect.Descriptor instead.
func (*NearbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_vrom_engine_proto_rawDescGZIP(), []int{0}
}

func (x *NearbyRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *NearbyRequest) GetRadiusKm() uint32 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type NearbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*NearbyEntity        `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	H3Index       string                 `protobuf:"bytes,2,opt,name=h3_index,json=h3Index,proto3" json:"h3_index,omitempty"` // The H3 cell of the search center
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyResponse) Reset() {
	*x = NearbyResponse{}
	mi := &file_proto_vrom_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyResponse) ProtoMessage() {}

func (x *NearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vrom_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyResponse.ProtoReflect.Descriptor instead.
func (*NearbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_vrom_engine_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyResponse) GetEntities() []*NearbyEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *NearbyResponse) GetH3Index() string {
	if x != nil {
		return x.H3Index
	}
	return ""
}

type NearbyEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	H3Index       string                 `protobuf:"bytes,2,opt,name=h3_index,json=h3Index,proto3" json:"h3_index,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,3,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyEntity) Reset() {
	*x = NearbyEntity{}
	mi := &file_proto_vrom_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyEntity) ProtoMessage() {}

func (x *NearbyEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vrom_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyEntity.ProtoReflect.Descriptor instead.
func (*NearbyEntity) Descriptor() ([]byte, []int) {
	return file_proto_vrom_engine_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NearbyEntity) GetH3Index() string {
	if x != nil {
		return x.H3Index
	}
	return ""
}

func (x *NearbyEntity) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Points        []*Location            `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_proto_vrom_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vrom_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_vrom_engine_proto_rawDescGZIP(), []int{3}
}

func (x *RouteRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RouteRequest) GetPoints() []*Location {
	if x != nil {
		return x.Points
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_vrom_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vrom_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_vrom_engine_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptimizedIds  []string               `protobuf:"bytes,1,rep,name=optimized_ids,json=optimizedIds,proto3" json:"optimized_ids,omitempty"`
	TotalDistance float64                `protobuf:"fixed64,2,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_proto_vrom_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vrom_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_vrom_engine_proto_rawDescGZIP(), []int{5}
}

func (x *RouteResponse) GetOptimizedIds() []string {
	if x != nil {
		return x.OptimizedIds
	}
	return nil
}

func (x *RouteResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

var File_proto_vrom_engine_proto protoreflect.FileDescriptor

const file_proto_vrom_engine_proto_rawDesc = "" +
	"\n" +
	"\x17proto/vrom_engine.proto\x12\x04vrom\"P\n" +
	"\rNearbyRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\rR\bradiusKm\"[\n" +
	"\x0eNearbyResponse\x12.\n" +
	"\bentities\x18\x01 \x03(\v2\x12.vrom.NearbyEntityR\bentities\x12\x19\n" +
	"\bh3_index\x18\x02 \x01(\tR\ah3Index\"Z\n" +
	"\fNearbyEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bh3_index\x18\x02 \x01(\tR\ah3Index\x12\x1f\n" +
	"\vdistance_km\x18\x03 \x01(\x01R\n" +
	"distanceKm\"Q\n" +
	"\fRouteRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12&\n" +
	"\x06points\x18\x02 \x03(\v2\x0e.vrom.LocationR\x06points\">\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"[\n" +
	"\rRouteResponse\x12#\n" +
	"\roptimized_ids\x18\x01 \x03(\tR\foptimizedIds\x12%\n" +
	"\x0etotal_distance\x18\x02 \x01(\x01R\rtotalDistance2}\n" +
	"\x0eMatchingEngine\x123\n" +
	"\bSolveTSP\x12\x12.vrom.RouteRequest\x1a\x13.vrom.RouteResponse\x126\n" +
	"\tGetNearby\x12\x13.vrom.NearbyRequest\x1a\x14.vrom.NearbyResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_vrom_engine_proto_rawDescOnce sync.Once
	file_proto_vrom_engine_proto_rawDescData []byte
)

func file_proto_vrom_engine_proto_rawDescGZIP() []byte {
	file_proto_vrom_engine_proto_rawDescOnce.Do(func() {
		file_proto_vrom_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vrom_engine_proto_rawDesc), len(file_proto_vrom_engine_proto_rawDesc)))
	})
	return file_proto_vrom_engine_proto_rawDescData
}

var file_proto_vrom_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_vrom_engine_proto_goTypes = []any{
	(*NearbyRequest)(nil),  // 0: vrom.NearbyRequest
	(*NearbyResponse)(nil), // 1: vrom.NearbyResponse
	(*NearbyEntity)(nil),   // 2: vrom.NearbyEntity
	(*RouteRequest)(nil),   // 3: vrom.RouteRequest
	(*Location)(nil),       // 4: vrom.Location
	(*RouteResponse)(nil),  // 5: vrom.RouteResponse
}
var file_proto_vrom_engine_proto_depIdxs = []int32{
	2, // 0: vrom.NearbyResponse.entities:type_name -> vrom.NearbyEntity
	4, // 1: vrom.RouteRequest.points:type_name -> vrom.Location
	3, // 2: vrom.MatchingEngine.SolveTSP:input_type -> vrom.RouteRequest
	0, // 3: vrom.MatchingEngine.GetNearby:input_type -> vrom.NearbyRequest
	5, // 4: vrom.MatchingEngine.SolveTSP:output_type -> vrom.RouteResponse
	1, // 5: vrom.MatchingEngine.GetNearby:output_type -> vrom.NearbyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vrom_engine_proto_init() }
func file_proto_vrom_engine_proto_init() {
	if File_proto_vrom_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vrom_engine_proto_rawDesc), len(file_proto_vrom_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vrom_engine_proto_goTypes,
		DependencyIndexes: file_proto_vrom_engine_proto_depIdxs,
		MessageInfos:      file_proto_vrom_engine_proto_msgTypes,
	}.Build()
	File_proto_vrom_engine_proto = out.File
	file_proto_vrom_engine_proto_goTypes = nil
	file_proto_vrom_engine_proto_depIdxs = nil
}
